{
    "auth.error.incorrect_login_or_password": "The username or password is incorrect.",
    "auth.error.not_auth_or_token_expired": "You are not logged in, or the lifetime of the session token has come to an end.",
    "auth.error.you_already_auth": "You are already logged in.",
    "auth.error.creating_user_details": "The user was not created in the database in the table UserDetails.",
    "auth.error.creating_user": "The user was not created in the database in the table Users.",
    "auth.error.session_id_not_exists": "There is no unique session identifier.",

    "auth.error.user_with_email_already_exists": "A user with a postal address {{email}} already exists.",
    "auth.error.user_with_phone_already_exists": "The user with the phone number {{phone}} already exists.",
    "auth.error.session_id_not_exists_on_deleted_session": "The user's session ID is missing (session={{session}}).",

    "photos.error.user_not_found": "User not exists.",
    "photos.error.sharp_avatar_path_not_found": "The path to the compressed avatar was not transmitted.",
    "photos.error.sharp_photo_path_not_found":  "The path to the compressed photo was not transmitted.",
    "photos.error.sharp_photo_paths_not_found": "Compressed photos were not found.",
    "photos.error.delete_photo_path_not_found": "The path for deleting the photo was not passed.",
    "photos.error.photo_not_found": "The photo was not found.",
    "photos.error.photos_not_found": "Images were not transmitted for compression.",
    "photos.error.sharped_photo_with_error": "An error occurred when cropping images: {{errorMessage}}",

    "files.error.message_id_not_found": "Не передан id сообщения.",
    "files.error.files_not_found": "Files have not been transferred.",
    "files.error.file_path_open_not_found": "The path for opening the file was not passed.",
    "files.error.file_path_download_not_found": "The file download path was not passed.",
    "files.error.file_not_found": "The file was not found.",

    "friends.error.get_friends_count": "An error occurred when receiving the number of friend requests.",
    "friends.error.get_possible_friends": "An error occurred when getting recommended friends.",
    "friends.error.get_all_friends": "An error occurred when getting all the friends.",
    "friends.error.get_friends_online": "An error occurred when getting friends online.",
    "friends.error.get_subscribers": "An error occurred while receiving subscribers.",
    "friends.error.get_incoming_requests": "An error occurred when receiving incoming friendship requests.",
    "friends.error.get_outgoing_requests": "An error occurred when receiving outgoing friendship requests.",
    "friends.error.search_friends": "An error occurred while searching for possible friends.",
    "friends.error.unknown_type_friends": "The type of friends received was not recognized.",

    "friends.error.friend_id_not_found": "No user information was found, it is possible that this is a temporary chat.",
    "friends.error.subscribed_id_not_found": "The ID of the user being subscribed to has not been transmitted.",
    "friends.error.unsubscribed_id_not_found": "The user's unsubscribe ID was not transmitted.",
    "friends.error.added_id_not_found": "The ID of the user we accept as a friend was not transmitted.",
    "friends.error.left_to_subscribed_id_not_found": "The ID of the user we are leaving in subscribers has not been transmitted.",
    "friends.error.deleted_id_not_found": "The ID of the user we are deleting from friends has not been transmitted.",
    "friends.error.blocked_id_not_found": "The ID of the blocked user was not transmitted.",
    "friends.error.check_blocked_id_not_found": "The ID of the verified user was not transmitted.",

    "users.error.user_not_found": "The user was not found.",
    "users.error.user_details_not_found": "Additional information about the user was not found.",
    "users.error.user_id_not_found": "The user's ID was not transmitted.",
    "users.error.user_with_id_not_found": "The user with id={{id}} was not found.",

    "messages.error.get_unread_messages": "An error occurred when receiving unread messages.",
    "messages.error.user_id_in_message_not_found": "Your unique identifier was not transmitted in the message object.",
    "messages.error.chat_id_in_message_not_found": "The unique chat ID was not passed in the message object.",
    "messages.error.message_id_not_found": "The unique identifier of the message was not transmitted.",
    "messages.error.empty_edit_message_without_files": "Error when changing the message. It cannot be empty without attached files.",
    "messages.error.deleted_message_id_not_found": "The unique identifier of the message being deleted was not transmitted.",
    "messages.error.your_already_delete_this_message": "This message has already been deleted by you.",

    "chats.error.chat_id_not_found": "The unique chat ID was not transmitted.",
    "chats.error.partner_id_not_found": "The unique identifier of the interlocutor was not transmitted.",
    "chats.error.partner_not_found": "The chat interlocutor was not found.",
    "chats.error.deleted_chat_id_not_found": "The unique identifier of the private chat being deleted was not transmitted.",
    "chats.error.users_in_chat_not_found": "No users were found in the {{chat}} chat.",
    "chats.error.chat_not_found": "The chat with the ID {{chat}} was not found.",    

    "socket.disconnecting": "In the process of disconnecting the socket connection ({{reason}}).",
    "socket.socket_disconnected_with_reason": "The socket with the connection ID {{socketId}} was disconnected due to: {{reason}}.",

    "socket.error.user_with_id_not_exists": "User with id={{userId}} not exists.",
    "socket.error.user_id_not_found": "The user ID was not transmitted.",
    "socket.error.not_correct_friends_action_type": "Incorrect type of action when working with friends.",
    "socket.error.cannot_find_call": "It is impossible to end the call because it has not been found. It may have already been completed.",
    "socket.error.not_correct_user_id_in_socket": "The user ID={{user To}} is not suitable. You must use the notify Me method.",
    "socket.error.update_last_seen": "An error occurred when updating the time of the user's last login.",
    "socket.error.socket_work": "An error occurred while working with the socket.",
    "socket.error.engine_socket": "Abnormal disconnection of the socket with the {{code}}.\nRequest object: {{req}}.\nError text: {{message}}.\nAdditional context: {{context}}.",

    "database.start": "The connection to the database has been successfully established.",
    "database.close": "The database connection has been successfully closed.",
    "database.error.close": "Closing the database connection failed.",
    "database.error.connect": "The connection to the database failed with an error.",

    "redis.connection_successfull": "The connection to the Redis client has been successfully established.",
    "redis.start_to_work": "The Redis client is ready to work.",
    "redis.stopped": "The Redis client has been stopped.",
    "redis.reconnection": "The Redis client is reconnecting...",
    "redis.new_pair_is_set": "New pair [{{key}}:{{value}}] successfully written to Redis.",
    "redis.key_successfull_deleted": "The key [{{key}}] has been successfully deleted from Redis.",

    "redis.error.client_connect": "Connection to the Redis database failed: ",
    "redis.error.client_work": "Error in the Redis client: ",
    "redis.error.get_value": "An error occurred when getting the key value [{{key}}] by Redis.",
    "redis.error.setting_new_pair": "An error occurred when writing a new pair [{{key}}:{{value}}] to Redis.",
    "redis.error.deleted_key": "An error occurred when deleting the [{{key}}] key from Redis.",

    "server_started": "The server instance is running on port: {{port}} in mode: {{mode}}.",
    "start_server_error": "An error occurred when starting the server instance",

    "error.unhandled_sync": "An unhandled error in synchronous code",
    "error.unhandled_async": "An unhandled error in asynchronous code",
    "error.initialize_i18n": "An error occurred while initializing the i18n package."
}